In [126]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [127]:
arr=np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [128]:
arr2d=arr.reshape(15,2)
arr2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin. 

In [129]:
arr3d = np.random.randint(1,100,60).reshape(2,-1,3)
arr3d
     

array([[[99, 20, 68],
        [44, 72, 27],
        [55, 34, 91],
        [28, 96, 31],
        [34, 27, 59],
        [36, 81, 28],
        [57, 72, 42],
        [93, 85, 88],
        [89, 60, 17],
        [98, 15, 33]],

       [[54, 54, 90],
        [57, 36, 69],
        [41, 36, 29],
        [85, 33,  8],
        [84, 13, 34],
        [85,  2, 87],
        [58,  8, 88],
        [33, 89, 22],
        [92, 14, 13],
        [ 3, 48, 44]]])

 3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [130]:
arr2d = np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [131]:
arr2d.shape

(5, 4)

In [132]:
arr=arr2d.reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
arr.shape

(20,)

In [134]:
arr.ndim

1

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [135]:

arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
for x in arr2d:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]


In [137]:

for x in arr2d:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9


In [138]:
for x in np.nditer(arr2d):
  print(x)

0
1
2
3
4
5
6
7
8
9


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun. Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [139]:
arr1 = np.array([5,10,15,20,25,30])
arr2 = np.array([1,2,3,4,5,6])

In [140]:
arr1

array([ 5, 10, 15, 20, 25, 30])

In [141]:
arr2

array([1, 2, 3, 4, 5, 6])

In [142]:
arr1+arr2

array([ 6, 12, 18, 24, 30, 36])

In [143]:
arr1-arr2

array([ 4,  8, 12, 16, 20, 24])

In [144]:
arr1*arr2

array([  5,  20,  45,  80, 125, 180])

In [145]:
arr1/arr2

array([5., 5., 5., 5., 5., 5.])

6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [146]:
arr = np.random.randint(0,100, 10)
arr
     

array([69, 80, 70, 34, 24, 39,  1, 90, 59, 50])

In [147]:
arr.sum()

516

In [148]:
arr.mean()

51.6

In [149]:
arr.var()

677.0400000000001

In [150]:
arr.std()

26.019992313603787

 7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [151]:
arr1=np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [152]:
arr2=np.arange(500,531)
arr2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [153]:
np.concatenate([arr1,arr2] , axis = 0 )

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın. 

In [154]:
arr1=np.arange(15,51)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50])

In [155]:
arr2=np.arange(10,101)
arr2

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [156]:
arr3=np.concatenate([arr1,arr2] , axis = 0 )
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [157]:
arr3[25:51] = 888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve 320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [158]:
arr1=np.arange(40)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [159]:
arr2d=arr1.reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [160]:
arr2=np.arange(320,360)
arr2

array([320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
       333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345,
       346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358,
       359])

In [161]:
arr2dd=arr2.reshape(8,5)
arr2dd

array([[320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [162]:
arr3=np.concatenate([arr2d,arr2dd] , axis = 0 )
arr3

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [163]:
arr3=np.concatenate([arr2d,arr2dd] , axis = 1 )
arr3

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın. 

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [93]:
arr=np.array( [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [94]:
np.where(arr == 5)

(array([ 5, 13]),)

 12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [96]:
arr=np.array( [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [100]:
np.where(arr % 2 == 0 )

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun. 

In [101]:
arr=np.array( [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [102]:
np.where(arr > 4 )

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun

In [103]:
np.where(arr % 5 == 0 )

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin 

In [104]:
np.random.randint(85 , 101 )

98

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [110]:
arr = np.random.randint(10,100,9)
arr

array([77, 69, 66, 62, 26, 90, 95, 52, 30])

In [113]:
arr1=arr.reshape(3,3)
arr1

array([[77, 69, 66],
       [62, 26, 90],
       [95, 52, 30]])

In [114]:
arr1.shape

(3, 3)

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [115]:
arr = np.random.randint(35,60)
arr

37

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [119]:
np.random.choice([3,8,10,53],(2,5))

array([[10,  3,  8,  3,  8],
       [53,  3, 53,  8,  3]])