1. NumPy kütüphanesi np kısaltması ile import edin

In [52]:
import numpy as np

2. 10 tane 0 değerinden oluşan bir array oluşturun

In [3]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. 10 tane 1 değerinden oluşan bir array oluşturun

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. 10 tane 5 değerinden oluşan bir array oluşturun

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım
 

In [6]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil)

In [7]:
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım

In [13]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. 3x3 boyutlarında birim matris oluşturun

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun.

 NOT: Değerler random seçildiği için sizin sonucunuz aşağıdaki çıktıdan farklı olacaktır

In [16]:
np.random.rand(1)

array([0.80759688])

10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım.

  NOT: Sizin cevabınız aşağıdaki çıktıdan farklı olacaktır

In [17]:
np.random.rand(25)

array([0.89147531, 0.45106649, 0.49826466, 0.76750628, 0.81311059,
       0.05079996, 0.94391337, 0.08262019, 0.23033922, 0.55427743,
       0.51311787, 0.87901419, 0.9393804 , 0.24917785, 0.1100398 ,
       0.85037965, 0.83597583, 0.80098551, 0.22123568, 0.80082575,
       0.41541605, 0.40759388, 0.91382006, 0.62797192, 0.77381252])

11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın

In [58]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun:

In [59]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

NumPy Indexing and Selection
Aşağıdaki matris sıradaki sorular için bizim başlangıç matrisimiz. (Aşağıdaki kod hücresini çalıştırarak devam edin.), devamında sorduğumuz soruları cevaplamaya çalışın:

# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

In [43]:
import numpy as np

In [44]:
mat = np.arange(1,26).reshape(5,5) 
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

13. Aşağıda verilen matrisleri oluşturmaya çalışın.

  Çıktıların üstündeki kod hücresini çalıştırmayın, aksi takdirde çıktıları göremezsiniz

14. Write code that reproduces the output shown below.

In [35]:
mat=np.random.randint(20 , 21 )
mat

20

15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

NumPy Operations
18. Mat arrayindeki bütün değerlerin toplamını bulun

In [45]:
mat.sum()

325

19. Mat arrayindeki değerlerin standart sapmasını bulun
 

In [46]:
mat.std()

7.211102550927978

20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun